### ISSUE TITLE
Docker image with previewers for local setup

### ISSUE THREAD

**Issue by gschmutz** [gdcc/dataverse-previewers#90]
This week I have implemented a solution to run the previewers locally as a docker container. Have it ready in my local setup using docker compose

```yaml
  #  ================================== Dataverse Previewers Provider ========================================== #
  dataverse-previewers-provider:
    image: trivadis/dataverse-previewers-provider:latest
    container_name: dataverse-previewers-provider
    hostname: dataverse-previewers-provider
    labels:
      com.platys.name: dataverse
      com.platys.description: Dataverse Previewers
      com.platys.webapp.title: Dataverse Previewers
      com.platys.webapp.url: http://dataplatform:28395/previewers/
    ports:
      - 28395:8080
    environment:
      - NGINX_HTTP_PORT=8080
      - PREVIEWERS_PROVIDER_URL=http://${PUBLIC_IP}:28395
      - VERSIONS="v1.4,betatest"
    volumes:
      - ./data-transfer:/data-transfer
    restart: unless-stopped
```

It uses the localinstall.sh at container startup time, so that it is possible to define the versions which should be supported. 

Interested in a PR?
